CREATE TABLE IF NOT EXISTS `USER` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '회원 고유 번호 (시스템용)',
	`email` VARCHAR(100) NOT NULL UNIQUE COMMENT '로그인에 사용할 이메일 아이디',
	`password` VARCHAR(255) NOT NULL COMMENT '암호화된 비밀번호',
	`phone_number` VARCHAR(20) NOT NULL UNIQUE COMMENT '국제 전화번호 (예: +821012345678)',
	`oauth_provider` VARCHAR(20) COMMENT 'GOOGLE, KAKAO, APPLE 등',
	`oauth_id` VARCHAR(255) COMMENT '소셜 로그인 고유 ID',
	`created_at` DATETIME NOT NULL COMMENT '가입 일자',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `PROFILE` (
	`profile_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT UNSIGNED NOT NULL COMMENT '이 프로필을 소유한 유저',
	`nickname` VARCHAR(50) NOT NULL COMMENT '채팅방에 보여지는 이름',
	`status_message` VARCHAR(100),
	`profile_image_url` VARCHAR(500) COMMENT '프로필 사진 경로',
	`profile_type` VARCHAR(20) NOT NULL COMMENT '프로필 종류 (MAIN, MULTI, OPEN_FRIENDS, OPEN_CUSTOM 등)',
	`created_at` TIMESTAMP NOT NULL,
	`updated_at` TIMESTAMP NOT NULL,
	PRIMARY KEY(`profile_id`),
	CONSTRAINT `uq_user_profile` UNIQUE (`profile_id`, `user_id`)
);


CREATE TABLE IF NOT EXISTS `AUTH_SESSION` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT UNSIGNED NOT NULL UNIQUE COMMENT 'UNIQUE라서 유저당 세션 row가 항상 1개 → 신규 로그인 시 UPSERT로 기존 세션 자동 교체',
	`device_id` VARCHAR(255) NOT NULL COMMENT '현재 활성 디바이스 식별자',
	`refresh_token` VARCHAR(500) NOT NULL COMMENT '재발급용 토큰 (평문 저장 금지, 해시 저장 권장)',
	`issued_at` DATETIME NOT NULL COMMENT '세션 발급 시각',
	`expired_at` DATETIME NOT NULL COMMENT '세션 만료 시각',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `FRIEND` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '관계 고유 번호',
	`user_id` BIGINT UNSIGNED NOT NULL COMMENT '친구를 추가한 유저 번호',
	`friend_id` BIGINT UNSIGNED NOT NULL COMMENT '친구로 추가된 유저 번호',
	`status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, HIDDEN, BLOCKED, FAVORITE',
	`alias` VARCHAR(50) COMMENT '내가 지정한 친구 별칭 (PROFILE.nickname과 동일 길이 기준)',
	`target_profile_id` BIGINT UNSIGNED COMMENT ' 이 친구에게만 보여줄 내 전용 프로필. PROFILE.profile_id FK',
	`created_at` DATETIME NOT NULL COMMENT '친구가 된 일자',
	PRIMARY KEY(`id`),
	CONSTRAINT `FRIEND_unique_0` UNIQUE (`user_id`, `friend_id`)
);


CREATE TABLE IF NOT EXISTS `CHAT_ROOM` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '채팅방 고유 번호',
	`room_name` VARCHAR(100) NOT NULL COMMENT '채팅방 이름',
	`room_type` VARCHAR(20) NOT NULL COMMENT '값 예시: ''DIRECT'' (1:1), ''GROUP'' (일반 단톡방), ''OPEN_DIRECT'' (오픈 1:1), ''OPEN_GROUP'' (오픈 그룹방), ''MY'' (나와의 채팅)',
	`created_at` DATETIME NOT NULL COMMENT '채팅방 생성 일자',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `ROOM_PARTICIPANT` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '채팅방-유저 매핑 고유 번호',
	`room_id` BIGINT UNSIGNED NOT NULL COMMENT '어떤 채팅방인지',
	`user_id` BIGINT UNSIGNED NOT NULL COMMENT '어떤 유저가 참가중인지',
	`profile_id` BIGINT NOT NULL,
	`joined_at` DATETIME NOT NULL COMMENT '채팅방 입장 시간',
	`last_read_message_id` BIGINT NOT NULL COMMENT '어떤 메시지까지 읽었는지',
	`custom_room_name` VARCHAR(100) COMMENT '유저별 커스텀 채팅방 이름 (CHAT_ROOM.room_name과 동일 길이)',
	`is_muted` BOOLEAN NOT NULL DEFAULT false COMMENT '알림 끄기 여부',
	`is_pinned` BOOLEAN NOT NULL DEFAULT false COMMENT '채팅방 상단 고정 여부',
	`background_image_url` VARCHAR(500) COMMENT '유저별 배경 이미지 (PROFILE.profile_image_url과 동일 길이)',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `MESSAGE` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '메시지 고유 번호',
	`room_id` BIGINT UNSIGNED NOT NULL COMMENT '어떤 채팅방에서 보낸 메시지인지',
	`sender_id` BIGINT UNSIGNED NOT NULL COMMENT '누가 보낸 메시지인지',
	`message_type` VARCHAR(20) NOT NULL COMMENT '메시지 종류 (TEXT, IMAGE, FILE, EMOJI, GIFT)',
	`is_deleted` BOOLEAN NOT NULL DEFAULT false COMMENT '메세지 삭제 상태',
	`created_at` DATETIME NOT NULL COMMENT '메시지 전송 시간',
	`deleted_at` DATETIME COMMENT '만약 삭제되었다면, 언제 삭제되었는지',
	`parent_message_id` BIGINT COMMENT '만약 이 메세지가 답장 메세지라면, 어떤 메세지가 원본 메세지인지 (일반 메세지라면 NULL값 대입)',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `MESSAGE_TEXT_CONTENT` (
	`message_id` BIGINT UNSIGNED NOT NULL COMMENT '메세지 고유 번호',
	`content` TEXT(65535) NOT NULL COMMENT '텍스트 내용',
	PRIMARY KEY(`message_id`)
);


CREATE TABLE IF NOT EXISTS `FILE_METADATA` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`message_id` BIGINT NOT NULL COMMENT '어떤 채팅에 첨부된 파일인지',
	`file_url` VARCHAR(255) NOT NULL COMMENT ' AWS S3에 저장된 실제 파일 다운로드 주소',
	`original_name` VARCHAR(255) NOT NULL COMMENT '사용자가 올린 실제 파일명',
	`file_size` BIGINT NOT NULL COMMENT '파일 용량',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `MESSAGE_LOG` (
	`log_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '로그 아이디',
	`message_id` BIGINT NOT NULL,
	`room_id` BIGINT NOT NULL,
	`sender_id` BIGINT NOT NULL,
	`action_type` VARCHAR(255) NOT NULL COMMENT '''CREATE'', ''UPDATE'', ''DELETE'' 등 어떤 행동이었는지 기록',
	`raw_content` TEXT(65535) NOT NULL,
	`created_at` TIMESTAMP NOT NULL COMMENT '로그 기록 시각',
	PRIMARY KEY(`log_id`)
);


CREATE TABLE IF NOT EXISTS `EMOJI` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '이모티콘 고유 번호',
	`image_url` VARCHAR(255) NOT NULL COMMENT '이코티콘 이미지 파일 경로',
	`category` VARCHAR(100) NOT NULL COMMENT '이모티콘 카테코리 명',
	`created_at` DATETIME NOT NULL COMMENT '등록 일자',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `EMOJI_METADATA` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '메타데이터 고유 번호',
	`message_id` BIGINT NOT NULL COMMENT '어떤 채팅 메시지에 쓰인 이모티콘인지',
	`emoji_id` BIGINT UNSIGNED NOT NULL COMMENT '어떤 이모티콘을 사용했는가',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `USER_EMOJI` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '이모티콘 보유 로깅 고유 번호',
	`user_id` BIGINT UNSIGNED NOT NULL COMMENT '어떤 유저가 보유하고 있는지',
	`emoji_id` BIGINT NOT NULL COMMENT '어떤 이모티콘을 보유하고 있는지',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `USER_SUBSCRIPTION` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT UNSIGNED NOT NULL UNIQUE COMMENT '1유저당 1구독 레코드',
	`is_emoticon_plus_active` BOOLEAN NOT NULL DEFAULT false COMMENT '이모티콘 플러스 활성 여부',
	`expired_at` DATETIME COMMENT '구독 만료 일시',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `DEVICE_TOKEN` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT UNSIGNED NOT NULL,
	`device_token` VARCHAR(255) NOT NULL,
	`device_type` VARCHAR(20) NOT NULL COMMENT '(iOS, ANDROID)',
	`updated_at` TIMESTAMP NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `NOTIFICATION_SETTING` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT UNSIGNED NOT NULL UNIQUE,
	`is_enabled` BOOLEAN NOT NULL DEFAULT true,
	`is_sound` BOOLEAN NOT NULL DEFAULT true,
	`quiet_start_time` TIME,
	`quiet_end_time` TIME,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `CALL_LOG` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`room_id` BIGINT NOT NULL,
	`caller_id` BIGINT UNSIGNED NOT NULL COMMENT '발신자',
	`receiver_id` BIGINT UNSIGNED NOT NULL COMMENT '수신자',
	`call_type` VARCHAR(20) NOT NULL COMMENT '(VOICE, FACE)',
	`call_status` VARCHAR(20) NOT NULL COMMENT '(CONNECTED, REJECTED, MISSED, BUSY)',
	`duration_seconds` INTEGER NOT NULL COMMENT '(통화 시간(초), 미연결 시 0)',
	`created_at` DATETIME NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `GIFT_PRODUCT` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`product_name` VARCHAR(50) NOT NULL,
	`brand_name` VARCHAR(50) NOT NULL,
	`price` DECIMAL(10,2) NOT NULL,
	`image_url` VARCHAR(255),
	`created_at` DATETIME,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `GIFT_ORDER` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`sender_id` BIGINT UNSIGNED NOT NULL COMMENT '선물 보낸 사람',
	`receiver_id` BIGINT UNSIGNED NOT NULL COMMENT '선물 받는 사람',
	`product_id` BIGINT NOT NULL,
	`order_status` VARCHAR(20) NOT NULL COMMENT '(SUCCESS, CANCELLED, REFUNDED)',
	`created_at` DATETIME NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `VOUCHER` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`order_id` BIGINT NOT NULL UNIQUE,
	`voucher_code` VARCHAR(100) NOT NULL,
	`voucher_status` VARCHAR(20) NOT NULL COMMENT '(UNUSED, USED, EXPIRED)',
	`valid_until` DATETIME COMMENT '유효기간',
	`used_at` DATETIME,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `GIFT_METADATA` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '메타데이터 고유 번호',
	`message_id` BIGINT UNSIGNED NOT NULL UNIQUE COMMENT '어떤 메시지에 연결된 선물인지',
	`voucher_id` BIGINT UNSIGNED NOT NULL UNIQUE COMMENT '어떤 교환권이 전달됐는지',
	PRIMARY KEY(`id`)
);


ALTER TABLE `FRIEND`
ADD FOREIGN KEY(`user_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `FRIEND`
ADD FOREIGN KEY(`friend_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ROOM_PARTICIPANT`
ADD FOREIGN KEY(`room_id`) REFERENCES `CHAT_ROOM`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `MESSAGE`
ADD FOREIGN KEY(`room_id`) REFERENCES `CHAT_ROOM`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `FILE_METADATA`
ADD FOREIGN KEY(`message_id`) REFERENCES `MESSAGE`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `EMOJI_METADATA`
ADD FOREIGN KEY(`message_id`) REFERENCES `MESSAGE`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `EMOJI_METADATA`
ADD FOREIGN KEY(`emoji_id`) REFERENCES `EMOJI`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `USER_EMOJI`
ADD FOREIGN KEY(`user_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `USER_EMOJI`
ADD FOREIGN KEY(`emoji_id`) REFERENCES `EMOJI`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `MESSAGE_TEXT_CONTENT`
ADD FOREIGN KEY(`message_id`) REFERENCES `MESSAGE`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PROFILE`
ADD FOREIGN KEY(`user_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `MESSAGE`
ADD FOREIGN KEY(`sender_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ROOM_PARTICIPANT`
ADD FOREIGN KEY(`user_id`, `profile_id`) REFERENCES `PROFILE`(`user_id`, `profile_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DEVICE_TOKEN`
ADD FOREIGN KEY(`user_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `NOTIFICATION_SETTING`
ADD FOREIGN KEY(`user_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CALL_LOG`
ADD FOREIGN KEY(`room_id`) REFERENCES `CHAT_ROOM`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `GIFT_ORDER`
ADD FOREIGN KEY(`sender_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `GIFT_ORDER`
ADD FOREIGN KEY(`receiver_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `GIFT_ORDER`
ADD FOREIGN KEY(`product_id`) REFERENCES `GIFT_PRODUCT`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `VOUCHER`
ADD FOREIGN KEY(`order_id`) REFERENCES `GIFT_ORDER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CALL_LOG`
ADD FOREIGN KEY(`caller_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CALL_LOG`
ADD FOREIGN KEY(`receiver_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `AUTH_SESSION`
ADD FOREIGN KEY(`user_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `FRIEND`
ADD FOREIGN KEY(`target_profile_id`) REFERENCES `PROFILE`(`profile_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `GIFT_METADATA`
ADD FOREIGN KEY(`voucher_id`) REFERENCES `VOUCHER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `GIFT_METADATA`
ADD FOREIGN KEY(`message_id`) REFERENCES `MESSAGE`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `USER_SUBSCRIPTION`
ADD FOREIGN KEY(`user_id`) REFERENCES `USER`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;